Safe mediacodec bindings
rust-windowing/android-ndk-rs pull request #216
Opened 2022-01-14 12:49 UTC by zarik5

Add `MediaCodec` and `MediaFormat` bindings with most of their methods. Crypto and DRM support is not implemented.

**Testing**
Only the decoder code path is tested. [sample](https://github.com/alvr-org/ALVR/blob/master/alvr/experiments/client/src/video_decoder/mediacodec.rs)

**Note:** This PR needs to be rebased after #213 is merged

2022-01-24 12:43 UTC, MarijnS95 requested changes
For starters, there are a lot of unnecessary `as _` casts and typed initializations. Please either be explicit about a cast or remove it altogether.

Adding `#![warn(trivial_casts)]` at the top of this file (hopefully we can do that repo-wide at some point) will help you track these down.

2022-01-24 12:43 UTC, MarijnS95 commented on ndk/src/media/media_codec.rs
> +        let mut out_size: ffi::size_t = 0;
No need for the explicit typeS here.

2022-01-24 12:43 UTC, MarijnS95 commented on ndk/src/media/media_codec.rs
> +        let mut out: ffi::size_t = 0;
No need for the explicit type here.

2022-01-24 12:43 UTC, MarijnS95 commented on ndk/src/media/media_codec.rs
> +                &mut out_size as _,
These will coerce, no need for `as _`.

2022-01-24 15:22 UTC, MarijnS95 commented
Fwiw feel free to leave the warning at the top of the file for the meantime. I'll work out to combine that with #219.

2022-01-24 15:24 UTC, MarijnS95 commented
> ```
> cargo clippy -p ndk --target armv7-linux-androideabi --features api-level-30 --features media
> cargo clippy -p ndk --target aarch64-linux-android --features api-level-30 --features media
> ```

You may also use `x86_64`/`i686` as those have a different pointer type for `c_char` (`u8`), afaik `armv7` also has `i8` like `aarch64`?

2022-01-24 15:27 UTC, zarik5 commented
> You may also use x86_64/i686 as those have a different pointer type for c_char (u8), afaik armv7 also has i8 like aarch64?

Ok, tried and no extra warnings or errors.

2022-01-24 15:29 UTC, zarik5 commented
There are still some warnings because of unused imports when using api-level-24, not only from my code

2022-01-24 15:37 UTC, MarijnS95 commented
> There are still some warnings because of unused imports when using api-level-24, not only from my code

That is something we should perhaps build-test in the CI and fix? Mind opening a separate PR for that (or issue if nontrivial)?

2022-03-11 02:01 UTC, zarik5 commented
Can this PR be merged? The warnings can be addressed in a second moment.

2022-03-11 02:13 UTC, dvc94ch approved these changes

2022-03-12 11:25 UTC, dvc94ch commented
LGTM, thanks @zarik5

2022-03-12 11:26 UTC, merged

2022-03-16 22:09 UTC, MarijnS95 commented
I wasn't actually okay with this yet, but that's what I get for being on holiday. Doc comments with double instead of triple slashes, [`get_` prefixes](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter), changelog in the past tense and no reference to this PR, inconsistent `use` statements that are unused when certain features are not enabled, `enum` that doesn't [derive common traits like `Eq`](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits) but instead has a strange `matches!` (why aren't the flags modeled directly with a `#[repr(u32)]` enum?), and that's just the stylistic nits.

2022-03-16 22:41 UTC, dvc94ch commented
Sometimes things are good enough. But agree that it would be better with the changes you mentioned.

2022-03-16 22:49 UTC, MarijnS95 commented
If crates are going to be maintained (or at least PRs merged) with a "good is good enough" mentality I'll have to step down as a maintainer, as I can't be cleaning up behind peoples back to uphold an acceptable feeling of responsibility towards said project.

That is, unless there's clear agreement and documentation that a PR is dragging on too long (in terms of discussions, not silence), and is best merged in preparation for followup changes to land through separate PRs.

2022-03-17 08:47 UTC, zarik5 commented
I'm sorry @MarijnS95, I realize that things were rushed. I tried picking up the style around but I did a poor job. The wrong doc comments were the most glaring mistake for me. I think it would really help a PR checklist (not necessarily in this repo, you could link to a good one in another repo or website).

2022-03-21 10:20 UTC, MarijnS95 commented
I don't think a checklist for standard style errors really exists or make sense; it should all be caught by (locally runnable) CI tools like `clippy`. In the grand scheme of things I'd like to fail on many more default-allow (rustc or clippy) lint warnings, but it takes a ginormous effort to get this project to pass stricter lints initially :no_mouth: 

We could however use a checklist for obvious things like requiring a changelog entry if a PR modifies public-facing API/behaviour.

2022-03-21 10:22 UTC, MarijnS95 commented
In any case, my post above links at least twice to https://rust-lang.github.io/api-guidelines/ - that's a good starting place if you're looking for more guidance.