Added android:launchMode configurability
rust-windowing/android-ndk-rs pull request #96
Opened 2020-11-20 22:13 UTC by maxded

Fixes #95 - although it would nice to introduce a proper serialize + deserialize mechanism for generating the `AndroidManifest.xml`

Would love to see this released in `cargo-apk` immediately after as it's a must feature for a project that I'm working on. Thanks in advance! :)

2020-11-20 23:19 UTC, msiglreith approved these changes
thanks! please add an entry in the sample `toml` in the cargo-apk readme

2020-11-20 23:22 UTC, msiglreith commented
for releases, feel free to open a PR which bumps versions (incl dependencies) otherwise I will create one tomorrow

2020-11-20 23:34 UTC, maxded commented
Done!

2020-11-21 11:44 UTC, msiglreith requested changes
A few small points left then good to go.
Also please add a changelog entry to `cargo-apk` for 0.5.5 to be clear what changed (in the dependencies)

2020-11-21 11:44 UTC, msiglreith commented on cargo-apk/README.md
> +# Set the instruction of how the activity hsould be launched
```suggestion
# Set the instruction of how the activity should be launched
```

2020-11-21 11:44 UTC, msiglreith commented on ndk-build/CHANGELOG.md
>  # Unreleased
```suggestion
# 0.1.3 (2020-11-21)
```

2020-11-21 15:20 UTC, msiglreith commented on cargo-apk/CHANGELOG.md
> +# 0.1.3 (2020-11-21)
0.5.5

2020-11-21 15:58 UTC, msiglreith approved these changes

2020-11-21 16:10 UTC, merged